deployment:
  toLocal:
    enabled: false
    pathFetching: true              # By default the path will be automatically fetched.
    extensionBaseDir: null          # Define the extensionBaseDir if pathFetching is disabled and you still want to deploy locally
  toSsh:                            # Upload via SSH
    enabled: true
    host: "192.168.56.13"
    port: 22
    username: "stefanwalther"
    password: "Test1234"
    dest: "/cygdrive/c/Users/stefanwalther/Documents/Qlik/Sense/Extensions/qssample-export-classic"

